### ISSUE TITLE
Не удается запустить скрипт с несколькими сессиями. С одной все работает.

### ISSUE THREAD

**Issue by joden95** [Axcent-ape/IcebergAppBot#1]
Если я запускаю скрипт только с одной сессией, то все работет корректно. Если же я добавляю хотя бы еще одну сессию, то первая запускается корректно, а при запуске второй выбивает ошибку (текст ошибки ниже) и тем самым ломает весь скрипт. Подскажи, что я делаю не так или как доработать скрипт?

Select action:
1. Start soft
2. Get statistics
3. Create sessions

> 1
2024-06-16 23:19:15 | INFO     | 36 - Searched sessions: 2.
2024-06-16 23:19:15 | SUCCESS  | 84 - Search available accounts: 2.
2024-06-16 23:19:15 | INFO     | 65 - Checking accounts for valid...
2024-06-16 23:19:16 | SUCCESS  | 74 - Valid accounts: 2; Invalid: 0
2024-06-16 23:19:25 | INFO     | 54 - Thread 0 | user1.session | Sleep 1003 seconds...
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 489, in finish_recv
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 64] Указанное сетевое имя более недоступно

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 841, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 493, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] Указанное сетевое имя более недоступно

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kis\IcebergAppBot\main.py", line 38, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kis\IcebergAppBot\main.py", line 34, in main
    await asyncio.gather(*tasks)
  File "C:\Users\kis\IcebergAppBot\utils\starter.py", line 24, in start
    await iceberg.change_status(task['id'], 'in_work')
  File "C:\Users\kis\IcebergAppBot\utils\iceberg.py", line 134, in change_status
    resp = await self.session.patch(f'https://0xiceberg.store/api/v1/web-app/tasks/task/{task_id}/', json=json_data, pr
oxy=self.proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^
  File "C:\Users\kis\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 608, in _request
    await resp.start(conn)
  File "C:\Users\kis\AppData\Roaming\Python\Python311\site-packages\aiohttp\client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kis\AppData\Roaming\Python\Python311\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] Указанное сетевое имя более недоступно

**Comment by joden95** [comment]
??
